export const helpInformation: string[] = [
    '\n',
    'Commandes possibles : ',
    '\n',
    '!placer <ligne><colonne>[(h|v)] <lettres>',
    'La commande permet de placer un mot selon les coordonnées de départ.',
    '\n',
    '!échanger <lettres>',
    "La commande permet d'échanger des lettres qui sont contenus sur votre chevalets avec des lettres aléatoires de la réserve",
    '\n',
    '!réserve',
    "La commande permet d'afficher le contenu de la réserve avec ses lettres restantes",
    '\n',
    '!passer',
    'La commande permet de passer votre tour',
    '\n',
    '!indice',
    'La commande affiche trois possibilités de placement. Attention, il ne s’agit pas nécessairement des trois meilleures solutions existantes!',
];
