export const helpInformation: string[] = [
    '\n',
    'Commandes possibles : ',
    '\n',
    '!placer <ligne><colonne>[(h|v)] <lettres>',
    'Permet de placer un mot selon les coordonnées de départ.',
    '\n',
    '!échanger <lettres>',
    "Permet d'échanger vos lettres avec des lettres aléatoires de la réserve",
    '\n',
    '!réserve',
    "Permet d'afficher le contenu des lettres restantes de la réserve",
    '\n',
    '!passer',
    'Permet de passer votre tour.',
    '\n',
    '!indice',
    'Affiche trois possibilités de placement.',
    '\n',
    '!aide',
    'Affiche les différentes commandes du jeu possibles.',
    '\n',
];
